require 'open-uri'
require 'nokogiri'
require 'pry'
require 'colorize'
require 'json'

require_relative './beatles_mania/version'
require_relative './beatles_mania/cli'
require_relative './beatles_mania/song'
require_relative './beatles_mania/scraper'
